"use client";

import React, { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  ArrowLeft,
  CalendarDays,
  Sparkles,
  Play,
  RefreshCw,
  AlertTriangle,
  CheckCircle2,
  FlaskConical,
} from "lucide-react";
import { api, getToken, getUser, AuthUser } from "../../lib/api";

interface Cell {
  subject_code: string;
  subject_name: string;
  teacher: string;
  room: string;
  is_lab: boolean;
}
interface Grid {
  section: string;
  version: number;
  days: string[];
  periods: Record<string, string>; // period_no -> "09:00–09:55"
  cells: Record<string, Cell>; // "MON-1" -> Cell
}
interface SectionRow {
  id: number;
  name: string;
}
interface GenerateResult {
  status: string;
  version?: number;
  lessons?: number;
  load_gap?: number;
  wall_time_s?: number;
  reasons?: string[];
}

// deterministic pastel per subject code
const PALETTE = [
  "bg-indigo-500/15 border-indigo-500/30 text-indigo-300",
  "bg-emerald-500/15 border-emerald-500/30 text-emerald-300",
  "bg-amber-500/15 border-amber-500/30 text-amber-300",
  "bg-sky-500/15 border-sky-500/30 text-sky-300",
  "bg-rose-500/15 border-rose-500/30 text-rose-300",
  "bg-violet-500/15 border-violet-500/30 text-violet-300",
  "bg-teal-500/15 border-teal-500/30 text-teal-300",
  "bg-orange-500/15 border-orange-500/30 text-orange-300",
];
function colorFor(code: string): string {
  let h = 0;
  for (const ch of code) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return PALETTE[h % PALETTE.length];
}

export default function TimetablePage() {
  const router = useRouter();
  const [user, setUser] = useState<AuthUser | null>(null);
  const [sections, setSections] = useState<SectionRow[]>([]);
  const [selected, setSelected] = useState<string>("");
  const [grid, setGrid] = useState<Grid | null>(null);
  const [generating, setGenerating] = useState(false);
  const [flash, setFlash] = useState<{ kind: "ok" | "err"; text: string } | null>(null);
  const [noTimetable, setNoTimetable] = useState(false);

  const loadGrid = useCallback(async (name: string) => {
    try {
      const g = await api<Grid>(`/timetable/section/${encodeURIComponent(name)}`);
      setGrid(g);
      setNoTimetable(false);
    } catch (e: unknown) {
      setGrid(null);
      const msg = e instanceof Error ? e.message : "";
      setNoTimetable(msg.includes("No timetable"));
      if (!msg.includes("No timetable")) setFlash({ kind: "err", text: msg });
    }
  }, []);

  useEffect(() => {
    if (!getToken()) {
      router.replace("/login");
      return;
    }
    setUser(getUser());
    (async () => {
      try {
        const secs = await api<SectionRow[]>("/setup/sections");
        setSections(secs);
        if (secs.length > 0) {
          setSelected(secs[0].name);
          await loadGrid(secs[0].name);
        }
      } catch (e: unknown) {
        setFlash({ kind: "err", text: e instanceof Error ? e.message : "Load failed" });
      }
    })();
  }, [router, loadGrid]);

  const generate = async () => {
    setGenerating(true);
    setFlash(null);
    try {
      const r = await api<GenerateResult>("/timetable/generate", { method: "POST" });
      setFlash({
        kind: "ok",
        text: `Generated v${r.version}: ${r.lessons} lessons, load gap ${r.load_gap}, solved in ${r.wall_time_s}s (provably clash-free).`,
      });
      if (selected) await loadGrid(selected);
    } catch (e: unknown) {
      // 422 carries the infeasibility explanation
      const msg = e instanceof Error ? e.message : "Generation failed";
      setFlash({ kind: "err", text: msg });
    } finally {
      setGenerating(false);
    }
  };

  const periods = grid ? Object.keys(grid.periods).map(Number).sort((a, b) => a - b) : [];

  return (
    <div className="min-h-screen p-6 relative overflow-x-hidden">
      <div className="absolute top-0 right-1/4 w-[500px] h-[300px] bg-indigo-600/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-6xl mx-auto relative">
        {/* header */}
        <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
          <div className="flex items-center space-x-4">
            <Link href="/" className="glass-card rounded-xl p-2.5 text-slate-400 hover:text-slate-200" title="Back to dashboard">
              <ArrowLeft className="h-5 w-5" />
            </Link>
            <div className="flex items-center space-x-3">
              <div className="bg-indigo-500/10 p-2 rounded-xl border border-indigo-500/20 text-indigo-400">
                <CalendarDays className="h-5 w-5" />
              </div>
              <div>
                <h1 className="font-bold text-xl text-slate-100">Timetable</h1>
                <p className="text-xs text-slate-400">
                  Generated by the Timetable Agent — OR-Tools CP-SAT, provably clash-free.
                </p>
              </div>
            </div>
          </div>

          <div className="flex items-center space-x-3">
            <select
              value={selected}
              onChange={(e) => {
                setSelected(e.target.value);
                loadGrid(e.target.value);
              }}
              className="glass-input rounded-xl px-4 py-2.5 text-sm"
            >
              {sections.map((s) => (
                <option key={s.id} value={s.name}>{s.name}</option>
              ))}
            </select>
            {user?.role === "admin" && (
              <button
                onClick={generate}
                disabled={generating}
                className="flex items-center space-x-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-60 text-white text-sm font-medium rounded-xl px-5 py-2.5 transition-colors"
              >
                {generating ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
                <span>{generating ? "Solving…" : "Generate Timetable"}</span>
              </button>
            )}
          </div>
        </div>

        {flash && (
          <div
            className={`flex items-start space-x-2 text-sm rounded-xl px-4 py-3 mb-4 border ${
              flash.kind === "ok"
                ? "text-emerald-400 bg-emerald-500/10 border-emerald-500/20"
                : "text-amber-400 bg-amber-500/10 border-amber-500/20"
            }`}
          >
            {flash.kind === "ok" ? <CheckCircle2 className="h-4 w-4 shrink-0 mt-0.5" /> : <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />}
            <span className="whitespace-pre-wrap">{flash.text}</span>
          </div>
        )}

        {/* grid */}
        {grid ? (
          <div className="glass-panel rounded-2xl overflow-x-auto">
            <div className="flex items-center justify-between px-5 pt-4">
              <h2 className="text-sm font-semibold text-slate-200">
                {grid.section} <span className="text-slate-500 font-normal">· version {grid.version}</span>
              </h2>
              <div className="flex items-center space-x-2 text-[10px] text-slate-500">
                <FlaskConical className="h-3.5 w-3.5" /><span>lab block</span>
              </div>
            </div>
            <table className="w-full mt-3">
              <thead>
                <tr className="border-b border-slate-800">
                  <th className="text-left text-[10px] text-slate-400 uppercase tracking-wider font-semibold px-4 py-3 w-28">Period</th>
                  {grid.days.map((d) => (
                    <th key={d} className="text-left text-[10px] text-slate-400 uppercase tracking-wider font-semibold px-3 py-3">{d}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                {periods.map((p) => (
                  <tr key={p}>
                    <td className="px-4 py-2 align-top">
                      <div className="text-sm font-semibold text-slate-300">P{p}</div>
                      <div className="text-[10px] text-slate-500">{grid.periods[String(p)]}</div>
                    </td>
                    {grid.days.map((d) => {
                      const cell = grid.cells[`${d}-${p}`];
                      return (
                        <td key={d} className="px-2 py-2 align-top">
                          {cell ? (
                            <div className={`rounded-lg border px-2.5 py-2 ${colorFor(cell.subject_code)}`}>
                              <div className="flex items-center justify-between">
                                <span className="text-xs font-bold font-mono">{cell.subject_code}</span>
                                {cell.is_lab && <FlaskConical className="h-3 w-3 opacity-70" />}
                              </div>
                              <div className="text-[10px] opacity-80 truncate max-w-[130px]">{cell.teacher}</div>
                              <div className="text-[10px] opacity-60">{cell.room}</div>
                            </div>
                          ) : (
                            <div className="rounded-lg border border-slate-800/40 px-2.5 py-4 text-center text-slate-700 text-[10px]">
                              free
                            </div>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="px-5 py-3" />
          </div>
        ) : (
          <div className="glass-panel rounded-2xl p-12 text-center">
            <Sparkles className="h-8 w-8 text-slate-600 mx-auto mb-3" />
            <p className="text-slate-400 text-sm">
              {noTimetable
                ? "No timetable generated yet."
                : "Select a section to view its timetable."}
            </p>
            {noTimetable && user?.role === "admin" && (
              <p className="text-slate-500 text-xs mt-2">
                Make sure Data Setup is complete, then click <b>Generate Timetable</b>.
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
